sudo: false

language: python

python:
  - 3.2
  - 3.3
  - 3.4
  - pypy3

install:
    - pip install scrutinizer-ocular webtest httmock requests
    # Coveralls 4.0 doesn't support Python 3.2
    - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
    - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi


before_script:
  - ./setup.py install

script:
  - coverage3 run run_tests.py

after_script:
  - ocular --data-file ".coverage"
